import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const navBar = ()=>{
  return(
      <nav className="bg-gray-950 text-emerald-400 text-2xl p-[1rem] flex justify-center items-center">
        <Link href="/">Logo</Link>
      </nav>
  )
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-950`}>
      {navBar()}
        {children}
      </body>
    </html>
  )
}
